### PR TITLE
Add gtk3 as dependency

### PR DESCRIPTION
**Pull request by birdsarah**
This adds gtk3 as a dependency.

This will fix our testing issue and also my current docker annoyances where I'm having to apt install gtk packes so that firefox will work.

### CODE REVIEW

**Comment by birdsarah** [comment]
Bummer. I guess the gtk3 addition isn't enough to make this run.

**Comment by birdsarah** [comment]
@isuruf - following from your comment on #11637. I thought we did too. But it's not working in this PR. Any suggestions?

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by birdsarah** [comment]
don't think this will ever work

**Comment by bollwyvl** [comment]
Oh, i think it might... i just don't have the patchelf skillz to do it yet.
might be a good sprint quest for the future... or if the build cache gets
sorted, just build from source.

**Comment by birdsarah** [comment]
> Oh, i think it might... i just don't have the patchelf skillz to do it yet.

that's a better way of putting it

**Pull request closed without merging**
