### PR TITLE
Update to 100.0.2

### PR DESCRIPTION
**Pull request by izahn**
Because I'm tired of firefox nagging me to update.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by birdsarah** [comment]
The tests are failing because the shas also need to be updated. Here's an example PR: https://github.com/conda-forge/firefox-feedstock/pull/93/files

**Comment by izahn** [comment]
Right thanks! 😵‍💫 🌴

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Review by birdsarah — APPROVED** [review]

**Pull request merged**
