### PR TITLE
Firefox 78.13.0esr

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by birdsarah** [comment]
🙏

**Comment by bollwyvl** [comment]
@birdsarah this _might_ be the end of the line for 78, as i think 91 is the new LTS. It's definitely served me well!

**Comment by birdsarah** [comment]
Indeed! Hopefully it's not too rough of a transition. Sadly still don't have [webgl in headless mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1375585) (my personal pet peeve)

**Comment by bollwyvl** [comment]
> too rough of a transition

ah, the axe has not _quite_ fallen: we have two more to go:

https://en.wikipedia.org/wiki/Firefox_version_history#Firefox_78.15esr

> webgl in headless mode

that will be _rad_ if your patch makes it in! rock on :guitar: !

**Pull request merged**
